<a href="https://colab.research.google.com/github/pauline-johnson/machine-learning/blob/master/Multiply_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiply Matrices
### This program multiplies two matrices and throws a custom exception if the matrices cannot be multiplied.

In [34]:
class Impossible(Exception):
  """Number of rows in matrix A do not match number of columns in matrix B"""
  pass

import numpy as np 

def multiplyMatrices(A,B):
  try:
    num_rows_A = np.shape(A)[0]
    num_cols_B = np.shape(B)[1]

    if(num_rows_A != num_cols_B):
      raise Impossible
    else:
      print(np.dot(A, B))
  except Impossible:
    print("Number of rows in matrix A do not match number of columns in matrix B")

a = ([1, 1, 1],[1 ,1, 1],[2, 2, 2]) 
b = ([2, 2, 2],[1, 1, 1],[1, 1, 1]) 
c = ([1, 1],[2, 2]) 

multiplyMatrices(a, b)
multiplyMatrices(a, c)




[[4 4 4]
 [4 4 4]
 [8 8 8]]
Number of rows in matrix A do not match number of columns in matrix B
